# Generated by APEBind. Do not edit directly.
from __future__ import annotations

import json
from pathlib import Path

from ._runtime import APEClient


_OPERATIONS = json.loads(r'''{
  "extract": {
    "command_path": [
      "--md"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "text",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": [
          {
            "flags": [
              "--config="
            ],
            "primary_flag": "--config=",
            "api_name": "config",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--password"
            ],
            "primary_flag": "--password",
            "api_name": "password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--encoding"
            ],
            "primary_flag": "--encoding",
            "api_name": "encoding",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pretty-print"
            ],
            "primary_flag": "--pretty-print",
            "api_name": "pretty_print",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      },
      {
        "path": [
          "--md"
        ],
        "token": "--md",
        "positionals": [
          {
            "api_name": "source",
            "required": true,
            "multiple": false
          }
        ],
        "options": []
      }
    ]
  },
  "extract_text": {
    "command_path": [
      "--text"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "text",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": [
          {
            "flags": [
              "--config="
            ],
            "primary_flag": "--config=",
            "api_name": "config",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--password"
            ],
            "primary_flag": "--password",
            "api_name": "password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--encoding"
            ],
            "primary_flag": "--encoding",
            "api_name": "encoding",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pretty-print"
            ],
            "primary_flag": "--pretty-print",
            "api_name": "pretty_print",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      },
      {
        "path": [
          "--text"
        ],
        "token": "--text",
        "positionals": [
          {
            "api_name": "source",
            "required": true,
            "multiple": false
          }
        ],
        "options": []
      }
    ]
  },
  "extract_xml": {
    "command_path": [
      "--xml"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "text",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": [
          {
            "flags": [
              "--config="
            ],
            "primary_flag": "--config=",
            "api_name": "config",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--password"
            ],
            "primary_flag": "--password",
            "api_name": "password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--encoding"
            ],
            "primary_flag": "--encoding",
            "api_name": "encoding",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pretty-print"
            ],
            "primary_flag": "--pretty-print",
            "api_name": "pretty_print",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      },
      {
        "path": [
          "--xml"
        ],
        "token": "--xml",
        "positionals": [
          {
            "api_name": "source",
            "required": true,
            "multiple": false
          }
        ],
        "options": []
      }
    ]
  },
  "extract_json": {
    "command_path": [
      "--json"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": [
          {
            "flags": [
              "--config="
            ],
            "primary_flag": "--config=",
            "api_name": "config",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--password"
            ],
            "primary_flag": "--password",
            "api_name": "password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--encoding"
            ],
            "primary_flag": "--encoding",
            "api_name": "encoding",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pretty-print"
            ],
            "primary_flag": "--pretty-print",
            "api_name": "pretty_print",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      },
      {
        "path": [
          "--json"
        ],
        "token": "--json",
        "positionals": [
          {
            "api_name": "source",
            "required": true,
            "multiple": false
          }
        ],
        "options": []
      }
    ]
  },
  "metadata": {
    "command_path": [
      "--metadata"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "text",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": [
          {
            "flags": [
              "--config="
            ],
            "primary_flag": "--config=",
            "api_name": "config",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--password"
            ],
            "primary_flag": "--password",
            "api_name": "password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--encoding"
            ],
            "primary_flag": "--encoding",
            "api_name": "encoding",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pretty-print"
            ],
            "primary_flag": "--pretty-print",
            "api_name": "pretty_print",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      },
      {
        "path": [
          "--metadata"
        ],
        "token": "--metadata",
        "positionals": [
          {
            "api_name": "source",
            "required": true,
            "multiple": false
          }
        ],
        "options": []
      }
    ]
  },
  "detect": {
    "command_path": [
      "--detect"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "text",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": [
          {
            "flags": [
              "--config="
            ],
            "primary_flag": "--config=",
            "api_name": "config",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--password"
            ],
            "primary_flag": "--password",
            "api_name": "password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--encoding"
            ],
            "primary_flag": "--encoding",
            "api_name": "encoding",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pretty-print"
            ],
            "primary_flag": "--pretty-print",
            "api_name": "pretty_print",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      },
      {
        "path": [
          "--detect"
        ],
        "token": "--detect",
        "positionals": [
          {
            "api_name": "source",
            "required": true,
            "multiple": false
          }
        ],
        "options": []
      }
    ]
  },
  "detect_language": {
    "command_path": [
      "--language"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "text",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": [
          {
            "flags": [
              "--config="
            ],
            "primary_flag": "--config=",
            "api_name": "config",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--password"
            ],
            "primary_flag": "--password",
            "api_name": "password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--encoding"
            ],
            "primary_flag": "--encoding",
            "api_name": "encoding",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pretty-print"
            ],
            "primary_flag": "--pretty-print",
            "api_name": "pretty_print",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      },
      {
        "path": [
          "--language"
        ],
        "token": "--language",
        "positionals": [
          {
            "api_name": "source",
            "required": true,
            "multiple": false
          }
        ],
        "options": []
      }
    ]
  }
}''')
_RUNTIME = json.loads(r'''{
  "env_unset": []
}''')
_CLIENT = APEClient(
    Path(__file__).with_name('bin') / 'tika.com',
    _OPERATIONS,
    _RUNTIME,
)


def extract(
    source,
    config=None,
    password=None,
    encoding=None,
    pretty_print=False,
):
    return _CLIENT.invoke(
        'extract',
        {
            'source': source,
            'config': config,
            'password': password,
            'encoding': encoding,
            'pretty_print': pretty_print,
        },
    )


def extract_text(
    source,
    config=None,
    password=None,
    encoding=None,
    pretty_print=False,
):
    return _CLIENT.invoke(
        'extract_text',
        {
            'source': source,
            'config': config,
            'password': password,
            'encoding': encoding,
            'pretty_print': pretty_print,
        },
    )


def extract_xml(
    source,
    config=None,
    password=None,
    encoding=None,
    pretty_print=False,
):
    return _CLIENT.invoke(
        'extract_xml',
        {
            'source': source,
            'config': config,
            'password': password,
            'encoding': encoding,
            'pretty_print': pretty_print,
        },
    )


def extract_json(
    source,
    config=None,
    password=None,
    encoding=None,
    pretty_print=False,
):
    return _CLIENT.invoke(
        'extract_json',
        {
            'source': source,
            'config': config,
            'password': password,
            'encoding': encoding,
            'pretty_print': pretty_print,
        },
    )


def metadata(
    source,
    config=None,
    password=None,
    encoding=None,
    pretty_print=False,
):
    return _CLIENT.invoke(
        'metadata',
        {
            'source': source,
            'config': config,
            'password': password,
            'encoding': encoding,
            'pretty_print': pretty_print,
        },
    )


def detect(
    source,
    config=None,
    password=None,
    encoding=None,
    pretty_print=False,
):
    return _CLIENT.invoke(
        'detect',
        {
            'source': source,
            'config': config,
            'password': password,
            'encoding': encoding,
            'pretty_print': pretty_print,
        },
    )


def detect_language(
    source,
    config=None,
    password=None,
    encoding=None,
    pretty_print=False,
):
    return _CLIENT.invoke(
        'detect_language',
        {
            'source': source,
            'config': config,
            'password': password,
            'encoding': encoding,
            'pretty_print': pretty_print,
        },
    )


def raw(arguments: list[str], persistent: bool = False):
    return _CLIENT.raw(arguments, persistent=persistent)
