// Generated by APEBind. Do not edit directly.
import type {
  APEProcessResult,
  ProcessSession,
  RawOptions,
} from './_runtime.js';

export interface ClientOptions {
  environment?: Readonly<Record<string, string | undefined>>;
}

export function createClient(options?: ClientOptions): import('./_runtime.js').APEClient;


export interface ExtractParameters {
  source: string;
  config?: string;
  password?: string;
  encoding?: string;
  prettyPrint?: boolean;
}

export function extract(
  parameters: ExtractParameters,
): Promise<string>;


export interface ExtractTextParameters {
  source: string;
  config?: string;
  password?: string;
  encoding?: string;
  prettyPrint?: boolean;
}

export function extractText(
  parameters: ExtractTextParameters,
): Promise<string>;


export interface ExtractXmlParameters {
  source: string;
  config?: string;
  password?: string;
  encoding?: string;
  prettyPrint?: boolean;
}

export function extractXml(
  parameters: ExtractXmlParameters,
): Promise<string>;


export interface ExtractJsonParameters {
  source: string;
  config?: string;
  password?: string;
  encoding?: string;
  prettyPrint?: boolean;
}

export function extractJson(
  parameters: ExtractJsonParameters,
): Promise<unknown>;


export interface MetadataParameters {
  source: string;
  config?: string;
  password?: string;
  encoding?: string;
  prettyPrint?: boolean;
}

export function metadata(
  parameters: MetadataParameters,
): Promise<string>;


export interface DetectParameters {
  source: string;
  config?: string;
  password?: string;
  encoding?: string;
  prettyPrint?: boolean;
}

export function detect(
  parameters: DetectParameters,
): Promise<string>;


export interface DetectLanguageParameters {
  source: string;
  config?: string;
  password?: string;
  encoding?: string;
  prettyPrint?: boolean;
}

export function detectLanguage(
  parameters: DetectLanguageParameters,
): Promise<string>;

export function raw(
  arguments_: readonly unknown[],
  options?: RawOptions,
): Promise<APEProcessResult | ProcessSession>;
