// Generated by APEBind. Do not edit directly.
import { fileURLToPath } from 'node:url';

import { APEClient } from './_runtime.js';

const OPERATIONS = {
  "extract": {
    "command_path": [
      "--md"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "text",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": [
          {
            "flags": [
              "--config="
            ],
            "primary_flag": "--config=",
            "api_name": "config",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--password"
            ],
            "primary_flag": "--password",
            "api_name": "password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--encoding"
            ],
            "primary_flag": "--encoding",
            "api_name": "encoding",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pretty-print"
            ],
            "primary_flag": "--pretty-print",
            "api_name": "prettyPrint",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      },
      {
        "path": [
          "--md"
        ],
        "token": "--md",
        "positionals": [
          {
            "api_name": "source",
            "required": true,
            "multiple": false
          }
        ],
        "options": []
      }
    ]
  },
  "extractText": {
    "command_path": [
      "--text"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "text",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": [
          {
            "flags": [
              "--config="
            ],
            "primary_flag": "--config=",
            "api_name": "config",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--password"
            ],
            "primary_flag": "--password",
            "api_name": "password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--encoding"
            ],
            "primary_flag": "--encoding",
            "api_name": "encoding",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pretty-print"
            ],
            "primary_flag": "--pretty-print",
            "api_name": "prettyPrint",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      },
      {
        "path": [
          "--text"
        ],
        "token": "--text",
        "positionals": [
          {
            "api_name": "source",
            "required": true,
            "multiple": false
          }
        ],
        "options": []
      }
    ]
  },
  "extractXml": {
    "command_path": [
      "--xml"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "text",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": [
          {
            "flags": [
              "--config="
            ],
            "primary_flag": "--config=",
            "api_name": "config",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--password"
            ],
            "primary_flag": "--password",
            "api_name": "password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--encoding"
            ],
            "primary_flag": "--encoding",
            "api_name": "encoding",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pretty-print"
            ],
            "primary_flag": "--pretty-print",
            "api_name": "prettyPrint",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      },
      {
        "path": [
          "--xml"
        ],
        "token": "--xml",
        "positionals": [
          {
            "api_name": "source",
            "required": true,
            "multiple": false
          }
        ],
        "options": []
      }
    ]
  },
  "extractJson": {
    "command_path": [
      "--json"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": [
          {
            "flags": [
              "--config="
            ],
            "primary_flag": "--config=",
            "api_name": "config",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--password"
            ],
            "primary_flag": "--password",
            "api_name": "password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--encoding"
            ],
            "primary_flag": "--encoding",
            "api_name": "encoding",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pretty-print"
            ],
            "primary_flag": "--pretty-print",
            "api_name": "prettyPrint",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      },
      {
        "path": [
          "--json"
        ],
        "token": "--json",
        "positionals": [
          {
            "api_name": "source",
            "required": true,
            "multiple": false
          }
        ],
        "options": []
      }
    ]
  },
  "metadata": {
    "command_path": [
      "--metadata"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "text",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": [
          {
            "flags": [
              "--config="
            ],
            "primary_flag": "--config=",
            "api_name": "config",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--password"
            ],
            "primary_flag": "--password",
            "api_name": "password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--encoding"
            ],
            "primary_flag": "--encoding",
            "api_name": "encoding",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pretty-print"
            ],
            "primary_flag": "--pretty-print",
            "api_name": "prettyPrint",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      },
      {
        "path": [
          "--metadata"
        ],
        "token": "--metadata",
        "positionals": [
          {
            "api_name": "source",
            "required": true,
            "multiple": false
          }
        ],
        "options": []
      }
    ]
  },
  "detect": {
    "command_path": [
      "--detect"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "text",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": [
          {
            "flags": [
              "--config="
            ],
            "primary_flag": "--config=",
            "api_name": "config",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--password"
            ],
            "primary_flag": "--password",
            "api_name": "password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--encoding"
            ],
            "primary_flag": "--encoding",
            "api_name": "encoding",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pretty-print"
            ],
            "primary_flag": "--pretty-print",
            "api_name": "prettyPrint",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      },
      {
        "path": [
          "--detect"
        ],
        "token": "--detect",
        "positionals": [
          {
            "api_name": "source",
            "required": true,
            "multiple": false
          }
        ],
        "options": []
      }
    ]
  },
  "detectLanguage": {
    "command_path": [
      "--language"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "text",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": [
          {
            "flags": [
              "--config="
            ],
            "primary_flag": "--config=",
            "api_name": "config",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--password"
            ],
            "primary_flag": "--password",
            "api_name": "password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--encoding"
            ],
            "primary_flag": "--encoding",
            "api_name": "encoding",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pretty-print"
            ],
            "primary_flag": "--pretty-print",
            "api_name": "prettyPrint",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      },
      {
        "path": [
          "--language"
        ],
        "token": "--language",
        "positionals": [
          {
            "api_name": "source",
            "required": true,
            "multiple": false
          }
        ],
        "options": []
      }
    ]
  }
};
const RUNTIME = {
  "env_unset": []
};

export function createClient({ environment = {} } = {}) {
  return new APEClient(
    fileURLToPath(new URL('./bin/tika.com', import.meta.url)),
    OPERATIONS,
    RUNTIME,
    environment,
  );
}

const CLIENT = createClient();

export async function extract(parameters = {}) {
  return CLIENT.invoke('extract', parameters);
}

export async function extractText(parameters = {}) {
  return CLIENT.invoke('extractText', parameters);
}

export async function extractXml(parameters = {}) {
  return CLIENT.invoke('extractXml', parameters);
}

export async function extractJson(parameters = {}) {
  return CLIENT.invoke('extractJson', parameters);
}

export async function metadata(parameters = {}) {
  return CLIENT.invoke('metadata', parameters);
}

export async function detect(parameters = {}) {
  return CLIENT.invoke('detect', parameters);
}

export async function detectLanguage(parameters = {}) {
  return CLIENT.invoke('detectLanguage', parameters);
}

export async function raw(arguments_, options = {}) {
  return CLIENT.raw(arguments_, options);
}
